### ISSUE TITLE
[Tracking] Roll out StatsBase 0.34 compat extension

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#1022]
Time to roll out StatsBase compat bump or extensions throughout the MLJ ecosystem.

### Step 1: Do this first:

- [x] MLJBase @ablaom

### Step 2: Generate the PRs (by giving CompatHelper a kick if necessary):

- [x] MLJTuning
- [x] MLJEnsembles
- [x] MLJIteration
- [x] MLJLinearModels 
- [x] MLJGLMInterface 
- [x] MLJMultivariateStatsInterface
- [x] EvoTrees (3rd party) 
- [x] MLJClusteringInterface
- [x] MLJDecisionTreeInterface 
- [x] NearestNeighborModels 
- [x] MLJFlux 
- [x] MLJLIBSVMInterface 
- [x] NaiveBayes.jl
- [x] MLJNaiveBayesInterface
- [x] MLJTSVDInterface
- [x] MLJText
- [x] MLJXGBoostInterface
- [x] OutlierDetectionNeighbors 
- [x] OutlierDetectionNetworks  
- [x] OutlierDetectionPython 
- [x] ParallelKMeans https://github.com/PyDataBlog/ParallelKMeans.jl/pull/119
- [x] PartialLeastSquaresRegressor 
- [x] BetaML (3rd party) https://github.com/sylvaticus/BetaML.jl/pull/54
- [x] LightGBM (3rd party)
- [x] MLJScikitLearnInterface 

### Step 3: Now released:

- [x] MLJTuning
- [x] MLJEnsembles
- [x] MLJIteration
- [x] MLJLinearModels 
- [x] MLJGLMInterface 
- [x] MLJMultivariateStatsInterface
- [x] EvoTrees (3rd party) 
- [x] MLJClusteringInterface
- [x] MLJDecisionTreeInterface 
- [x] NearestNeighborModels 
- [x] MLJFlux 
- [x] MLJLIBSVMInterface 
- [x] NaiveBayes; waiting on author to tag new release https://github.com/dfdx/NaiveBayes.jl/pull/60
- [x] MLJNaiveBayesInterface
- [x] MLJTSVDInterface
- [x] MLJText
- [x] MLJXGBoostInterface
- [x] OutlierDetectionNeighbors 
- [x] OutlierDetectionNetworks  
- [x] OutlierDetectionPython 
- [x] ParallelKMeans
- [x] PartialLeastSquaresRegressor 
- [x] BetaML (3rd party)
- [x] LightGBM (3rd party)
- [x] MLJScikitLearnInterface 
- [x] EvoLinear https://github.com/jeremiedb/EvoLinear.jl/issues/16
- [x] Optim https://github.com/JuliaNLSolvers/Optim.jl/pull/1040
- [x] TextAnalysis https://github.com/JuliaText/TextAnalysis.jl/issues/267
- [x] LatinHyperCubeSampling https://github.com/MrUrq/LatinHypercubeSampling.jl/issues/23

### Step 4:

- [x] MLJModels
- [ ] MLJ

**Comment by zsz00** [comment]
Optim released, @ablaom
