### ISSUE TITLE
[Tracking] Migration of measures MLJBase.jl -> StatisticalMeasures.jl

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#1053]
To do:

- [x] Locally run MLJTestIntegration/examples/bigtest/notebook.jl against all the PR's referenced below 
- [x] Merge https://github.com/JuliaAI/MLJBase.jl/pull/909
- [x] Tag new MLJBase release
- [x] Merge and tag https://github.com/JuliaAI/MLJFlow.jl/pull/21
- [x] Merge and tag https://github.com/JuliaAI/MLJEnsembles.jl/pull/30
- [x] Merge and tag https://github.com/JuliaAI/MLJTuning.jl/pull/194
- [x] Merge and tag https://github.com/JuliaAI/MLJIteration.jl/pull/56
- [x] Merge and tag https://github.com/alan-turing-institute/MLJ.jl/pull/1054 (MLJ.jl)

After this, many interface packages will need updates to their tests, but shouldn't need their source code updated.

**Comment by ablaom** [comment]
closed as completed
