### ISSUE TITLE
Towards 0.5.1

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#245]
- [x] (**Enhancement**) Update requirements for MLJBase and MLJModels to **eliminate the current cap of 0.5.2 on CategoricalArrays**. Among other things, this allows more recent versions of CSV and DataFrames to be used with MLJ, and eliminates some warnings.  (https://github.com/alan-turing-institute/MLJBase.jl/issues/44, PR #275)

- [x] (**Enhancement**) The MLJBase update also adds the **Brier score** for probabilistic classifiers

- [x] (**Bug**) Fix a bug with `|>` syntax for building learning networks (julia >= 0.3) (#253, PR #263 )

- [x] (**Bug**) Fix problem with loading most ScikitLearn classifiers (#252) 

- [x] (**Enhancement**) Allow specification of different resolutions for each dimension in a grid search (#269 , PR #278). Do `?Grid` for details. 

- [x] (**Enhancement**) Allow `selectcols(X, c)` to work on nodes in addition to tables `X`. So, if `X` is a node and `N=selectnode(X, c)`, then `N()` is the same as `select(X(), c)` (#271)
