### ISSUE TITLE
Towards 0.5.5

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#308]
- [x] (**Feature**) Enable sample weight support in performance evaluation, in tuning, in ensembling, in `@piplines`, in learning networks, and exported composite model types (PR #356)

- [x] (**Feature**) Update to MLJBase 0.8.4 to enable static transformations depending on user-specified parameters to be included in `@pipeline`s and `@from_network` exported composite models. Update the "Composing Models" section of the manual accordingly (#291, PR #350) 

- [x] (**Feature**) add stratified sampling (issue #108)
- [x] bump to 0.5.5
