### ISSUE TITLE
Towards stabilisation of the core API

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#318]
The purpose of this **"FYI"** issue is to articulate a number of personal priorities for stabilizing the core API in MLJBase - a preliminary triage for MLJBase 1.0, if you will.

I am assigning myself to these tasks. I fear if they are not addressed, then they willl cause much pain should my involvement in the project wane. 

*I will not be responding to any comments posted here.* Please provide any feedback by joining the discussion in one of the separate threads referenced below, or open a new topic-specific issue, thanks.

- [x] Enable model implementations to support sample weights. Actually, the interface part is done, but machines and their methods are now aware of this yet. (#177) 

- [x] Make `output_scitype` an  "inspectable" trait of supervised learners, to support those learners that transform as well as predict (https://github.com/alan-turing-institute/MLJModels.jl/issues/117)

- [ ] Enable model implementations to support on-line learning (#60)

- [x] Reorganize the MLJ stack to enhance scalability (https://github.com/alan-turing-institute/MLJ.jl/issues/317)

- [x] Tweak the machine interface to facilitate serialisation/deserialization of hyperparameters and learned parameters #138

**Comment by ablaom** [comment]
Closing in favour of #, the remaining item on my list. (Probably need a new list 😄 )
