### ISSUE TITLE
Towards 0.5.9

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#358]
* [x] Re-export `table` from MLJBase (#381) 

* [x] Add `learning_curve(model, args...; kwargs...)` which is equivalent to `learning_curve!(machine(model, args...); kwargs...)` (#377, PR #388)

* [x] Resolve minor issues #282, #283.

* [x] Allow `learning_curve!` to assign a default measure when none specified (#283)
