### ISSUE TITLE
For next minor release (breaking)

### ISSUE THREAD

**Issue by ablaom** [alan-turing-institute/MLJ.jl#470]
Upgrade to MLJBase 0.12.0 and MLJModels 0.9.0 to effect the following changes:

- [x] (**breaking**) suppress normalisation of measure weights (MLJBase PR #208)

- [x] (**breaking**) Shift the optional `rng` argument of iterator to first position (MLJBase #215)

- [x] (**mildly breaking**) Let all models (supervised and unsupervised) share a common set of traits. So, for example, unsupervised models now have the `target_scitype` trait (usually taking the value `Unknown`). For a list of the common traits, do `models()[1] |> keys |> collect` (https://github.com/alan-turing-institute/MLJBase.jl/issues/163). 

- [x] (**enhancement**) Add `sampler` wrapper for one-dimensional ranges, for random sampling from ranges using `rand` (MLJBase #213)

- [x] Change default value of `num_round` in XGBoost models from 1 to 100 (MLJModels PR #201)
